# Generated by Django 5.2.6 on 2025-10-04 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Memories',
            new_name='Memory',
        ),
    ]
