# Generated by Django 5.2.6 on 2025-10-05 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_memories_memory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuidador',
        ),
        migrations.AddField(
            model_name='user',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Caregiver', 'Caregiver'), ('Patient', 'Patient')], max_length=20, null=True),
        ),
    ]
