# Generated by Django 5.2.6 on 2025-10-07 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_cuidador_user_patient_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='type',
        ),
    ]
