# Generated by Django 5.2.7 on 2025-11-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_alzheimer_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alzheimer_level',
            field=models.CharField(blank=True, choices=[('Ninguno', 'None'), ('Leve', 'Mild'), ('Moderado', 'Moderate'), ('Severo', 'Severe')], max_length=10, null=True),
        ),
    ]
