# Generated by Django 5.2.7 on 2025-11-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_alzheimer_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Hombre', 'Male'), ('Mujer', 'Female')], max_length=10, null=True),
        ),
    ]
