# Generated by Django 5.2.7 on 2025-11-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('Message', 'Message'), ('Other', 'Other'), ('Emergency', 'Emergency')], max_length=20, null=True),
        ),
    ]
