# Generated by Django 5.2.7 on 2025-11-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='level',
            field=models.IntegerField(default=1, help_text='1=easy, 2=normal, 3=hard'),
        ),
    ]
