# Generated by Django 5.2.7 on 2025-11-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_achievement_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
