# Generated by Django 5.2.7 on 2025-11-27 23:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_card_created_by_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(help_text='Motivo de la solicitud', max_length=255)),
                ('start_datetime', models.DateTimeField(help_text='Fecha y hora de inicio del apoyo')),
                ('end_datetime', models.DateTimeField(help_text='Fecha y hora de fin del apoyo')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales para el cuidador suplente')),
                ('status', models.CharField(choices=[('En espera', 'En Espera'), ('Asignada', 'Asignada'), ('En curso', 'En Curso'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='En espera', help_text='Estado actual de la solicitud', max_length=20)),
                ('actual_start', models.DateTimeField(blank=True, help_text='Hora real de inicio', null=True)),
                ('actual_end', models.DateTimeField(blank=True, help_text='Hora real de finalización', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_caregiver', models.ForeignKey(blank=True, help_text='Cuidador asignado para dar el apoyo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(help_text='Cuidador que solicita el apoyo', on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Apoyo',
                'verbose_name_plural': 'Solicitudes de Apoyo',
                'ordering': ['-created_at'],
            },
        ),
    ]
