# Generated by Django 5.2.7 on 2025-11-28 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_supportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Paciente que será asignado temporalmente al cuidador suplente', limit_choices_to={'user_type': 'Patient'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_requests_as_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='assigned_caregiver',
            field=models.ForeignKey(blank=True, help_text='Cuidador asignado para dar el apoyo', limit_choices_to={'user_type': 'Caregiver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
