# Generated by Django 5.2.7 on 2025-11-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_locationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_token',
            field=models.CharField(blank=True, help_text='Expo push notification token', max_length=255, null=True),
        ),
    ]
