# Generated by Django 5.2.7 on 2025-11-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_user_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='safezone',
            name='safe_exit_active',
            field=models.BooleanField(default=False),
        ),
    ]
