POST http://127.0.0.1:8000/auth/users/ HTTP/1.1
Content-Type: application/json

{
    "email": "patient5@example.com",
    "username": "patient5",
    "password": "Test123456",
    "user_type": "Patient",
    "phone_number": "123456789",
    "age": 70,
    "gender": "Hombre",
    "alzheimer_level": "Moderado",
    "patient": null,
    "first_name": "Hola",
    "last_name": "xd"
}


