### Registro usuarios con campos: username, password, user_type, phone_number
POST http://127.0.0.1:8000/auth/users/ HTTP/1.1
Content-Type: application/json

{
    "username": "blur",
    "password": "xd123456",
    "user_type": "sd",
    "phone_number": "123",
    "user_type": "Caregiver"
}

### Obtiene JWT a partir de logearse (username, password)
POST http://127.0.0.1:8000/auth/jwt/create/ HTTP/1.1
Content-Type: application/json

{
    "email": "diego@gmail.com",
    "password": "1234"
}

### Logea usuario con JWT
GET http://127.0.0.1:8000/auth/users/me/ HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwMTQyMzc3LCJpYXQiOjE3NjAxNDIwNzgsImp0aSI6IjBhMDYzNWIwZTcxOTQ0YmQ5ZTU0OTQwNTJmZDJjMGJjIiwidXNlcl9pZCI6IjEifQ.nyLUv7KEWRv6mUGgqyFlpKDFTam3nj-2a-fesFi34HY

### Cerrar sesion
POST http://127.0.0.1:8000/auth/token/logout/ HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MzQwMTMyNCwiaWF0IjoxNzYwODA5MzI0LCJqdGkiOiI3ZTZkZWRlZWI3Mjg0Mjk1ODNiMjUwYzVjN2RmZmQyMCIsInVzZXJfaWQiOiIyIn0.2ss7-z7a14QUVpAD8Oq7HhlXLoMOyYB5onAT_-wDCTs