import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");
const ACCENT = "#FF7043";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#000" },
  overlay: { ...StyleSheet.absoluteFillObject },
  header: {
    position: "absolute",
    top: 60,
    left: 20,
    right: 20,
    flexDirection: "row",
    alignItems: "center",
    zIndex: 10,
  },
  headerText: {
    color: "#FFF",
    fontSize: 20,
    fontWeight: "700",
    marginLeft: 10,
  },
  scanBox: {
    alignSelf: "center",
    marginTop: 180,
    width: width * 0.7,
    height: width * 0.7,
    alignItems: "center",
    justifyContent: "center",
  },
  roundedBorder: {
    position: "absolute",
    width: "100%",
    height: "100%",
    borderWidth: 3,
    borderColor: ACCENT,
    borderRadius: 28,
    overflow: "hidden",
  },
  shadowLayer: {
    position: "absolute",
    width: "112%",
    height: "112%",
    borderRadius: 32,
    backgroundColor: "rgba(0,0,0,0.3)",
    shadowColor: ACCENT,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.7,
    shadowRadius: 16,
  },
  scanLine: {
    position: "absolute",
    left: 20,
    right: 20,
    height: 4,
    borderRadius: 2,
    backgroundColor: ACCENT,
    shadowColor: ACCENT,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 8,
    opacity: 0.95,
  },
  instruction: {
    color: "#FFF",
    fontSize: 16,
    textAlign: "center",
    marginTop: 24,
    opacity: 0.85,
  },
  rescanButton: {
    position: "absolute",
    bottom: 60,
    alignSelf: "center",
    flexDirection: "row",
    backgroundColor: ACCENT,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: "center",
    elevation: 3,
  },
  rescanText: { color: "#FFF", marginLeft: 8, fontWeight: "600" },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  btn: {
    backgroundColor: ACCENT,
    padding: 12,
    borderRadius: 8,
    marginTop: 10,
  },
  btnText: { color: "#FFF", fontWeight: "600" },
});
