import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F5F5F5" },

  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    alignItems: "center",
    paddingBottom: 12,
  },
  headerTitle: { fontSize: 24, fontWeight: "700", color: "#212121", flex: 1, textAlign: "center" },

  summaryBox: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "#FFF",
    paddingVertical: 16,
    marginHorizontal: 16,
    marginTop: 8,
    borderRadius: 16,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  summaryItem: { alignItems: "center", flex: 1 },
  summaryLabel: { fontSize: 12, color: "#757575", fontWeight: "500" },
  summaryValue: { fontSize: 24, color: "#1976D2", fontWeight: "700", marginTop: 4 },
  summaryDivider: { width: 1, height: 40, backgroundColor: "#E0E0E0" },

  cuidadoresSection: {
    marginTop: 16,
    backgroundColor: "#FFF",
    marginHorizontal: 16,
    borderRadius: 16,
    padding: 14,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 8,
  },
  sectionTitle: { fontSize: 16, fontWeight: "700", color: "#263238", flex: 1 },
  disponibleBadge: {
    backgroundColor: "#43A047",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  disponibleBadgeText: { color: "#FFF", fontSize: 12, fontWeight: "700" },

  cuidadoresScroll: { paddingRight: 16, gap: 12 },

  cuidadorCardCompact: {
    backgroundColor: "#F9F9F9",
    borderRadius: 12,
    padding: 12,
    width: 110,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E0E0E0",
    position: "relative",
  },
  avatarCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#1976D2",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  avatarText: { color: "#FFF", fontSize: 16, fontWeight: "700" },
  cuidadorNombre: { fontSize: 12, fontWeight: "600", color: "#212121", textAlign: "center" },
  ratingRow: { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 4 },
  ratingText: { fontSize: 11, color: "#455A64", fontWeight: "600" },
  etaText: { fontSize: 10, color: "#607D8B", marginTop: 2 },
  noDisponibleBadge: {
    position: "absolute",
    top: 6,
    right: 6,
    backgroundColor: "#EF5350",
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  noDisponibleText: { color: "#FFF", fontSize: 9, fontWeight: "700" },

  cuidadorCardExpanded: {
    flexDirection: "row",
    backgroundColor: "#FAFAFA",
    borderRadius: 12,
    padding: 12,
    marginVertical: 6,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    alignItems: "center",
  },
  cuidadorCardLeft: { marginRight: 12 },
  avatarCircleLarge: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#1976D2",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarTextLarge: { color: "#FFF", fontSize: 20, fontWeight: "700" },
  cuidadorCardCenter: { flex: 1 },
  cuidadorNombreLarge: { fontSize: 15, fontWeight: "700", color: "#212121" },
  ratingRowLarge: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 4 },
  ratingTextLarge: { fontSize: 13, color: "#455A64", fontWeight: "600" },
  experienciaText: { fontSize: 12, color: "#757575" },
  especialidadText: { fontSize: 12, color: "#1976D2", marginTop: 4 },
  distanciaText: { fontSize: 11, color: "#607D8B", marginTop: 2 },
  cuidadorCardRight: { marginLeft: 8 },
  seleccionarBtn: {
    backgroundColor: "#1976D2",
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  seleccionarBtnText: { color: "#FFF", fontSize: 13, fontWeight: "700" },

  sectionHeaderSolicitudes: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 18,
    marginTop: 16,
    marginBottom: 8,
    gap: 8,
  },

  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 48,
    marginHorizontal: 32,
  },
  emptyStateText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#757575",
    marginTop: 12,
  },
  emptyStateSubtext: {
    fontSize: 13,
    color: "#9E9E9E",
    marginTop: 8,
    textAlign: "center",
    lineHeight: 20,
  },

  card: {
    backgroundColor: "#FFF",
    marginHorizontal: 16,
    marginVertical: 8,
    padding: 16,
    borderRadius: 16,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  cardTitle: { fontWeight: "700", fontSize: 16, color: "#212121", flex: 1 },
  badge: {
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  badgeText: {
    color: "#FFF",
    fontWeight: "700",
    fontSize: 11,
  },

  cardDatesRow: { marginBottom: 8 },
  cardDateItem: { flexDirection: "row", alignItems: "center", marginVertical: 2 },
  cardText: { color: "#455A64", fontSize: 13 },
  cardTextSecondary: { color: "#607D8B", fontSize: 12, marginTop: 4 },

  suplementRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    backgroundColor: "#E3F2FD",
    padding: 8,
    borderRadius: 8,
  },
  suplementText: { color: "#1565C0", fontSize: 13, fontWeight: "600" },

  notaContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginTop: 8,
    backgroundColor: "#FFF8E1",
    padding: 8,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: "#FFA726",
  },
  cardNote: { fontStyle: "italic", color: "#F57C00", fontSize: 12, flex: 1 },

  postulacionesContainer: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#E0E0E0",
  },
  postulacionesTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1976D2",
    marginBottom: 8,
  },

  actionsRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
    marginTop: 12,
  },
  btn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
  },
  btnText: { color: "#FFF", fontWeight: "700", fontSize: 13 },

  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalBox: {
    backgroundColor: "#FFF",
    borderRadius: 20,
    padding: 20,
    width: "90%",
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#263238",
    marginBottom: 16,
    textAlign: "center",
  },
  input: {
    borderWidth: 1,
    borderColor: "#CFD8DC",
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    color: "#000",
    fontSize: 14,
  },
  modalButtons: { flexDirection: "row", justifyContent: "space-between", marginTop: 8 },
  modalBtn: {
    flex: 1,
    marginHorizontal: 6,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 4,
  },
  modalBtnText: { color: "#FFF", fontWeight: "700", fontSize: 14 },
});
