import { StyleSheet, Platform, StatusBar } from "react-native";
const TOP_PAD = Platform.OS === "android" ? StatusBar.currentHeight || 0 : 0;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FAFAFA" },
  header: {
    position: "absolute",
    top: 0,
    width: "100%",
    zIndex: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    backgroundColor: "rgba(255,255,255,0.95)",
    paddingBottom: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#212121",
  },
  legend: {
    position: "absolute",
    top: TOP_PAD + 55,
    alignSelf: "center",
    backgroundColor: "rgba(255,255,255,0.9)",
    flexDirection: "row",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    elevation: 4,
    gap: 14,
    zIndex: 20,
  },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 6 },
  legendDot: { width: 10, height: 10, borderRadius: 5 },
  legendText: { fontSize: 11, color: "#37474F", fontWeight: "600" },
  map: { flex: 1 },
  statusOverlay: {
    position: "absolute",
    top: TOP_PAD + 100,
    alignSelf: "center",
    zIndex: 20,
  },
  statusPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    elevation: 4,
  },
  statusText: { color: "#FFF", fontWeight: "700", fontSize: 12 },
  recenterBtn: {
    position: "absolute",
    right: 20,
    bottom: Platform.OS === "android" ? 180 : 160,
    backgroundColor: "#1976D2",
    padding: 10,
    borderRadius: 30,
    elevation: 10,
    marginBottom: 10,
  },
  bottomPanel: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    backgroundColor: "#FFF",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: Platform.OS === "android" ? 40 : 30,
    elevation: 10,
  },
  label: {
    textAlign: "center",
    fontWeight: "600",
    color: "#37474F",
    marginBottom: 10,
  },
  slider: { width: "100%", height: 40 },
  buttonsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  actionBtn: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    marginHorizontal: 6,
    paddingVertical: 12,
    borderRadius: 12,
  },
  actionText: { color: "#FFF", fontWeight: "700", fontSize: 14 },
  tip: {
    textAlign: "center",
    color: "#757575",
    fontStyle: "italic",
  },
  mensajeBox: {
    position: "absolute",
    top: "45%",
    alignSelf: "center",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 12,
    elevation: 8,
  },
  mensajeTexto: {
    color: "#FFF",
    fontWeight: "700",
    fontSize: 14,
    textAlign: "center",
  },
});
